### ISSUE TITLE
Mixing 2 templates

### ISSUE THREAD

**Issue by waclock** [creativetimofficial/ct-argon-dashboard-pro-react#1]
Hello, I'm aware that I'm not using the template, but I'm not sure where to contact you guys with the "premium support".

Right now we're implementing Material Kit Dashboard template, and I'm very interested in using a few components from Argon (I've bought both templates), however I'm not sure if there's any guidelines/recommendations on how to "mix" these two templates? 

Would you advice not to do so? I've realized that Material Kit uses JSS and bootstrap, while Argon uses SCSS and reactstrap, which makes me think it might not be so easy to "mix" these two templates, but I was wondering if you could think of any way to achieve this.

Best,

**Comment by einazare** [comment]
Hello there, @waclock ,

Thank you for your interest in working with our products and sorry for this late response.
I wasn't notified by Github when the issue was opened.
As you've guessed it, we wouldn't advise you using components from one product to another, since the stylings are different.

Best,
Manu
