### ISSUE TITLE
The navbar doesn't collapse in your pro example

### ISSUE THREAD

**Issue by C0DK** [creativetimofficial/ct-argon-dashboard-pro-react#12]
The navbar doesn't collapse in your pro example. It's pretty simple actually :P 

https://demos.creative-tim.com/argon-dashboard-pro-react/#/admin/dashboard <- the burger menu button doesn't seem to do anything. it works fine in your non-pro example 

https://demos.creative-tim.com/argon-dashboard-react/#/admin/index

**Comment by C0DK** [comment]
Also it isn't responsive on phones.

**Comment by einazare** [comment]
Hello there, @C0DK ,

Thank you for your interest in working with our products.
Why did you not follow our rules of engagement?
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/argon-dashboard-pro-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```
As you can see, we should close and ignore your issue, since you did not follow our rules.
I will leave this open for the time being, but next time your issue will be closed and ignored - Hope you can understand our situation.
Why we need you to follow our rules? For example, on the new-issue form, we have a question that asks for the device that you have made the tests. To continue my example, please look at the following video:
![argon-dashboard-pro-react-mobile](https://user-images.githubusercontent.com/26245512/68462865-231f2080-0216-11ea-99f7-4c3c1fd4ab13.gif)
I've made the test on a Huawei P10 Lite, as you can see, everything works perfectly (I had to convert the video to gif, to make it a bit smaller, that is why it is a bit pixeled). Maybe the issue is only on your type of device.

I will wait for further details.

Best,
Manu

**Comment by C0DK** [comment]
I initially looked at your website, but was guided to your github through some link that talked about issues here. I assumed it was the same link that guided me here, so didn't check it out when submitting this issue.

It seems to be quite a hostile way of interacting with paying customers that has the sole intention of bug reporting - I didn't *have* to do that. i fixed my bug by simply looking at your free example, and using the navbar from that. I'm sorry if my actions didn't portray my intentions. But please. 

It seems my problem was more of a UX than an actual bug. After playing around with your demo a third time i now understand how it works. I didn't realize that the bar expanded upon hovering, so when clicking the burger menu it seems to only move the main container, rather than the sidebar, so i was seeing the image below, which seemed rather buggy.
![image](https://user-images.githubusercontent.com/9048078/68590792-aac39400-048f-11ea-9685-147911efb400.png)

Having apparently never moved my mouse from the sidebar, i never realized the intended behavour. The same was the case on phone, when testing in firefox, it by default had the bar to the left open, and i didn't realize i had to click on the main container for it to close.

I simply did not understand how the system worked. 

Sorry for any inconvenience, i should have supplied a better description
