### ISSUE TITLE
Checkbox is absolutely empty

### ISSUE THREAD

**Issue by hung1998pro** [creativetimofficial/ct-argon-dashboard-pro-react#17]
Hi Creative Tim,
I just bought your Argon dashboard pro react. I have downloaded argon react pro version 1.1 . But After I installed all the required packages, I saw all the checkboxes are empty. Here are some pictures of my issue,  one is on the dashboard page, the other one is on the table page.
<img width="252" alt="empty_dashboard" src="https://user-images.githubusercontent.com/22428822/77748854-9ef9f800-7053-11ea-9d16-c9a9b961bfe0.png">
<img width="272" alt="empty_table" src="https://user-images.githubusercontent.com/22428822/77748857-a02b2500-7053-11ea-85e9-a9bf5e30d5d8.png">

**Comment by einazare** [comment]
Hello there, @hung1998pro ,

Please provide us with the following video:
* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run node -v
* Run npm -v
* [Mac/Ubuntu/Linux] Run npm run install:clean
* [Widnows] Run npm install
* [Widnows] Run npm start
* Showcase the issue

You can share it with us via wetransfer, and send the video to *** (if you do not want to make it public, since in the video will be shown your personal account on creative-tim).

Also, maybe before making the video, maybe you have just forgotten to add some of our styles: https://demos.creative-tim.com/argon-dashboard-pro-react/#/documentation/quick-start

Best,
Manu

**Comment by hung1998pro** [comment]
This is a warning message when I try to start the app

> WARNING: `text-emphasis-variant()` has been deprecated as of v4.4.0. It will be removed entirely in v5.
         on line 8 of src/assets/scss/bootstrap/mixins/_deprecate.scss, in mixin `deprecate`
         from line 16 of src/assets/scss/bootstrap/mixins/_text-emphasis.scss, in mixin `text-emphasis-variant`
         from line 48 of src/assets/scss/core/utilities/_text.scss
         from line 28 of src/assets/scss/custom/_utilities.scss
         from line 69 of stdin

When I used MS Edge to access the app, I could see the checkbox properly.
![image](https://user-images.githubusercontent.com/22428822/77764721-afb86700-706f-11ea-8c7d-bbe7061a2ef6.png)
But when I switched to chromium-browser like chrome, I can't see the checkbox. 

![image](https://user-images.githubusercontent.com/22428822/77765400-cb703d00-7070-11ea-9bd4-6e286d0d52ba.png)

Then, I tried to figure out what the problem is, I inspect the after element of checkbox label and i saw some overlap CSS code here
![image](https://user-images.githubusercontent.com/22428822/77770662-35d8ab80-7078-11ea-9acc-129fb0b089aa.png)

Afterward, I uncheck the first and second ones and then it works
![image](https://user-images.githubusercontent.com/22428822/77770826-733d3900-7078-11ea-99ee-55a33af92065.png)

So where can I fix my problem

**Comment by einazare** [comment]
Hello there, @hung1998pro ,

I've just tested the project, it works fine on all browsers.
Please provide us with the following video:
* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run node -v
* Run npm -v
* [Mac/Ubuntu/Linux] Run npm run install:clean
* [Widnows] Run npm install
* [Widnows] Run npm start
* Showcase the issue

You can share it with us via wetransfer, and send the video to *** (if you do not want to make it public, since in the video will be shown your personal account on creative-tim).

Best,
Manu

**Comment by hung1998pro** [comment]
Hi @EINazare ,
I've sent a video that followed your instruction, please take a look and let me know the solution as soon as possible.

**Comment by einazare** [comment]
Hello again, @hung1998pro ,

Please create a new folder under the `src/assets/scss`, named `custom-developement`.
Inside that, create a new scss file, named `_forms.scss`, inside that file add the following code:
```
.custom-checkbox-success .custom-control-input:checked ~ .custom-control-label::after {
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8' viewBox='0 0 8 8'%3e%3cpath fill='%23fff' d='M6.564.75l-3.59 3.612-1.538-1.55L0 4.26l2.974 2.99L8 2.193z'/%3e%3c/svg%3e");
}
```
And import that scss file inside `src/assets/scss/argon-dashboard-pro-react.scss` at the ned of the file.

That will do the trick.

Best,
Manu

**Comment by hung1998pro** [comment]
Thank you @EINazare ,
I've tried your solution and it did the trick, I will manually warning, info ... checkbox as well. 
![image](https://user-images.githubusercontent.com/22428822/77899867-63f00280-72a7-11ea-95a9-8a1af0fb9b49.png)
