### ISSUE TITLE
[Bug] Reactstrap Spinner works on regular but not PRO

### ISSUE THREAD

**Issue by mlehmann-sys** [creativetimofficial/ct-argon-dashboard-pro-react#26]
### Version
1.1.0
### Reproduction link
https://jsfiddle.net/5rbu476e/
### Operating System
Mac
### Device
Desktop
### Browser & Version
Chrome (all)
### Steps to reproduce
The JSFiddle I provided showed the DASHBOARD.JS example file code with a Spinner in it.  Just replace Dashboard.js in /src/views/pages/dashboards/Dashboard.js with this code for an example of a Spinner in a page.
This happens when you try to use the Spinner anywhere in the PRO version
### What is expected?
Well the spinner should show up.
### What is actually happening?
The spinner is not there.

---
### Solution
Not sure.  It is strange that it worked just fine on the regular version of the Argon dahboard but as soon as I moved to PRO, it does not work.

**Comment by einazare** [comment]
Hello there, @mlehmann-sys ,

Thank you for your interest in working with our products.
This issue was actually solved in our last update: https://github.com/creativetimofficial/ct-argon-dashboard-pro-react/releases/tag/v1.1.0

I honestly do not understand what changed, and why the issue started to persist again :|.

Please go inside `src/assets/scss/argon-dashboard-pro-react.scss` and replace the following bits of codes:
```
@import "bootstrap/utilities";
@import "bootstrap/print";
```
With
```
@import "bootstrap/utilities";
@import "bootstrap/spinners";
@import "bootstrap/print";
```

This will do the trick.

Please leave the issue opened and we'll add this solution in our next update as well.

Best,
Manu

**Comment by mlehmann-sys** [comment]
> Hello there, @mlehmann-sys ,
> 
> Thank you for your interest in working with our products.
> This issue was actually solved in our last update: https://github.com/creativetimofficial/ct-argon-dashboard-pro-react/releases/tag/v1.1.0
> 
> I honestly do not understand what changed, and why the issue started to persist again :|.
> 
> Please go inside `src/assets/scss/argon-dashboard-pro-react.scss` and replace the following bits of codes:
> 
> ```
> @import "bootstrap/utilities";
> @import "bootstrap/print";
> ```
> 
> With
> 
> ```
> @import "bootstrap/utilities";
> @import "bootstrap/spinners";
> @import "bootstrap/print";
> ```
> 
> This will do the trick.
> 
> Please leave the issue opened and we'll add this solution in our next update as well.
> 
> Best,
> Manu

This worked, thanks!
