### ISSUE TITLE
[Bug] Cannot import Nucleo Icon Pro Assets into "ni-<iconName>" structure 

### ISSUE THREAD

**Issue by VinLucero** [creativetimofficial/ct-argon-dashboard-pro-react#32]
### Version
Latest
### Reproduction link
https://www.clowte.com
### Operating System
OSX
### Device
Macbook Air
### Browser & Version
Chrome Latest
### Steps to reproduce
I love the "ni-<iconName>" system for importing SVGs from Nucleo so I purchased their paid Pro edition, but I cannot figure out how to import all of the pro assets into the "ni system"

I assume it has something to do with the CSS file below, but I cannot find a way to download/add the new Nucleo Pro SVGs to this system.

import "assets/vendor/nucleo/css/nucleo.css";

### What is expected?
I would like to be able to use all of the Nucleo Pro icons since I paid for them as recommended by Creative Tim Pro Argon.
### What is actually happening?
I cannot import the new, additional icon SVG assets into the ni icon system.

---

**Comment by einazare** [comment]
Hello there, @VinLucero ,

Thank you for your interest in working with our products.
Our product does not work with SVGs from Nucleo Icons, that is why we import that `.css` file.
So, in order to add new icons, you will need to check this part of their tutorial: https://nucleoapp.com/docs/exporting-icons#export-font
Also, in the base class input, you will need to add `ni` and in the class prefix input you will need to add `ni-`.
After downloading the export, you will have to add that exported files inside our product, I suggest `src/assets/vendor/nucleo-pro`.
And after that, you will go inside our `index.js` file, and import the css from the pro nucleo like so:
```
import "assets/vendor/nucleo-pro/css/nucleo.css";
```
You can add this line, right after the free icons from us.

If you will still have an issue with this, let me know.

Best,
Manu

**Comment by VinLucero** [comment]
I had to export as ni-pro instead of ni because the conflict caused the original icons to not show up, but otherwise working.
