### ISSUE TITLE
[Bug] Multiple Select not working

### ISSUE THREAD

**Issue by lmaldonadoch** [creativetimofficial/ct-argon-dashboard-pro-react#36]
### Version
1.2.0
### Reproduction link
https://demos.creative-tim.com/argon-dashboard-pro-react/#/admin/elements
### Operating System
MacOS BigSur
### Device
Macbook PRO (M1 chip)
### Browser & Version
Google Chrome Version 88.0.4324.192 (Official Build) (arm64)
### Steps to reproduce
1. go to the link provided.
2. Navigate to "Multiple Select" Section
3. Try to select multiple items
### What is expected?
User should be able to select multiple items from the list
### What is actually happening?
The list is not showing as a dropdown and you can not select multiple items.

---

**Comment by einazare** [comment]
Hello there, @lmaldonadoch ,

Thank you for your interest in working with our products.
The Multiple Select from the given page, is working as expected. Please take a look at it's counterpart from Bootstrap as well: https://getbootstrap.com/docs/4.6/components/forms/#form-controls
As you can see, we only took the Bootstrap components and changed their styling, but they work as those from Bootstrap.

I will close this issue since everything is working as expected.

Best,
Manu
