### ISSUE TITLE
[Bug] Navigation item labels are visible in small Sidebar

### ISSUE THREAD

**Issue by BusyBeans** [creativetimofficial/ct-argon-dashboard-pro-react#38]
### Version
1.2.0
### Reproduction link
https://demos.creative-tim.com/argon-dashboard-pro-react/?_ga=2.132908172.366707456.1621174177-214873037.1621174177#/
### Operating System
Windows
### Device
Laptop
### Browser & Version
Chrome, Firefox -latest
### Steps to reproduce
1. visit the dashoard from the [index page](https://demos.creative-tim.com/argon-dashboard-pro-react/?_ga=2.132908172.366707456.1621174177-214873037.1621174177#/)
2. toogle the sidebar to "small".
3. click on the brand logo to return to the index page
4. return to the dashboard again
5. the sidebar is still small, but the navigation item labels are visible.

(After I hover over the sidebar, everything looks ok again.)
### What is expected?
bugfix
### What is actually happening?
the sidebar navigation item labels are visible when the sidebar is small.

---

**Comment by BusyBeans** [comment]
![sidebar](https://user-images.githubusercontent.com/24841087/118509235-2743cc80-b730-11eb-8b98-cdf4f6536481.png)

**Comment by sajadevo** [comment]
**Hi Busy**
Thanks for using our products, its not actually a bug its a common thing thats happening when resizing the browser window only and it will not be visible on real devices, because there is a state that changes the sidenav width and when you open or close the sidenav on a small devices it have a different behavior and coming back to large size of the window its showing this.

So don't worry its working fine and there is no problem with this.

**All the best**
**Sajad**
